# Generated by Django 4.2.2 on 2023-06-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_catagory_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.catagory'),
            preserve_default=False,
        ),
    ]
